
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.1 EDK_P.15xf
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BUZZER_0_DEVICE_ID,
		XPAR_BUZZER_0_BASEADDR,
		XPAR_BUZZER_0_INTERRUPT_PRESENT,
		XPAR_BUZZER_0_IS_DUAL
	}
};


